### ISSUE TITLE
Sugestão quanto ao public.html

### ISSUE THREAD

**Issue by savioacp** [MultiWar/TCCV2#1]
Considere arrumar o arquivo public.html para melhor se adequar ao seu projeto. 
Algumas das inconveniênicias relacionadas à não configuração do arquivo são a falta de descrição em previews de aplicativos de mensagens, o 404 relacionado ao favicon.ico, o título de aba "React App" e a errada ideia de que existe um manifest.json e um logo192.png, causando uma impressão errada aos dispositivos que suportam a instalação de páginas web como aplicativos.

**Comment by MultiWar** [comment]
Tem razão, agradeço pelo comentário, Será corrigido no próximo commit,
